# Generated by Django 3.1.4 on 2020-12-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneScuola', '0002_auto_20201212_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='voti1',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='materia',
            name='voti2',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
