# Generated by Django 3.1.4 on 2020-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneScuola', '0003_auto_20201212_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.FloatField()),
                ('tipo', models.CharField(max_length=100)),
                ('media', models.IntegerField()),
                ('giorno', models.CharField(max_length=100)),
            ],
        ),
    ]
