# Generated by Django 3.1.4 on 2020-12-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneScuola', '0005_quadrimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50)),
                ('elenco', models.CharField(max_length=100000)),
                ('scadenza', models.CharField(max_length=15)),
            ],
        ),
    ]
